import type { IconType } from 'react-icons';
import {
  WiDaySunny,
  WiCloud,
  WiFog,
  WiSprinkle,
  WiRainMix,
  WiRain,
  WiSnow,
  WiSleet,
  WiShowers,
  WiThunderstorm,
} from 'react-icons/wi';

export const weatherCodeToIcon: Record<string, IconType> = {
  '0': WiDaySunny,
  '1': WiDaySunny,
  '2': WiCloud,
  '3': WiCloud,
  '45': WiFog,
  '48': WiFog,
  '51': WiSprinkle,
  '53': WiSprinkle,
  '55': WiSprinkle,
  '56': WiRainMix,
  '57': WiRainMix,
  '61': WiRain,
  '63': WiRain,
  '65': WiRain,
  '66': WiRainMix,
  '67': WiRainMix,
  '71': WiSnow,
  '73': WiSnow,
  '75': WiSnow,
  '77': WiSleet,
  '80': WiShowers,
  '81': WiShowers,
  '82': WiShowers,
  '85': WiSnow,
  '86': WiSnow,
  '95': WiThunderstorm,
  '96': WiThunderstorm,
  '99': WiThunderstorm,
};
